export const PORTFOLIO_REQUEST = "PORTFOLIO_REQUEST";
export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_FAIL = "PORTFOLIO_FAIL";

export const PORTFOLIO_UPDATE_REQUEST = "PORTFOLIO_UPDATE_REQUEST";
export const PORTFOLIO_UPDATE_SUCCESS = "PORTFOLIO_UPDATE_SUCCESS";
export const PORTFOLIO_UPDATE_FAIL = "PORTFOLIO_UPDATE_FAIL";
export const PORTFOLIO_UPDATE_RESET = "PORTFOLIO_UPDATE_RESET";
