export const QUALIFICATION_LIST_REQUEST = "QUALIFICATION_LIST_REQUEST";
export const QUALIFICATION_LIST_SUCCESS = "QUALIFICATION_LIST_SUCCESS";
export const QUALIFICATION_LIST_FAIL = "QUALIFICATION_LIST_FAIL";

export const QUALIFICATION_DETAILS_REQUEST = "QUALIFICATION_DETAILS_REQUEST";
export const QUALIFICATION_DETAILS_SUCCESS = "QUALIFICATION_DETAILS_SUCCESS";
export const QUALIFICATION_DETAILS_FAIL = "QUALIFICATION_DETAILS_FAIL";

export const QUALIFICATION_UPDATE_REQUEST = "QUALIFICATION_UPDATE_REQUEST";
export const QUALIFICATION_UPDATE_SUCCESS = "QUALIFICATION_UPDATE_SUCCESS";
export const QUALIFICATION_UPDATE_FAIL = "QUALIFICATION_UPDATE_FAIL";
export const QUALIFICATION_UPDATE_RESET = "QUALIFICATION_UPDATE_RESET";
