export const SOCIAL_PROFILES_REQUEST = "SOCIAL_PROFILES_REQUEST";
export const SOCIAL_PROFILES_SUCCESS = "SOCIAL_PROFILES_SUCCESS";
export const SOCIAL_PROFILES_FAIL = "SOCIAL_PROFILES_FAIL";

export const SOCIAL_PROFILE_DETAILS_REQUEST = "SOCIAL_PROFILE_DETAILS_REQUEST";
export const SOCIAL_PROFILE_DETAILS_SUCCESS = "SOCIAL_PROFILE_DETAILS_SUCCESS";
export const SOCIAL_PROFILE_DETAILS_FAIL = "SOCIAL_PROFILE_DETAILS_FAIL";

export const SOCIAL_PROFILE_UPDATE_REQUEST = "SOCIAL_PROFILE_UPDATE_REQUEST";
export const SOCIAL_PROFILE_UPDATE_SUCCESS = "SOCIAL_PROFILE_UPDATE_SUCCESS";
export const SOCIAL_PROFILE_UPDATE_FAIL = "SOCIAL_PROFILE_UPDATE_FAIL";
export const SOCIAL_PROFILE_UPDATE_RESET = "SOCIAL_PROFILE_UPDATE_RESET";
